// Native JNI bridge for original KataGo 10b on MediaTek Neuron MDLA.
// Input features must be GENERATED BY KATAGO, not inferred from GoBoard;
// no game search or model feature encoder is hidden in this bridge.
// Model packet exported by MiniGoCpp/tools/export_katago_neuron_full.py.
// Each instance compiles once and keeps the NeuronExecution alive.
#include <jni.h>
#include <dlfcn.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <string>
#include <vector>

struct NeuronModel;
struct NeuronCompilation;
struct NeuronExecution;
struct NeuronDevice;
struct NeuronOperandType {
    int32_t type;
    uint32_t dimensionCount;
    const uint32_t* dimensions;
    float scale;
    int32_t zeroPoint;
};

namespace {
constexpr uint32_t CONST_FLAG=1, INPUT_FLAG=2;
constexpr int BOARD_SIZE=19, SPATIAL_CHANNELS=22, GLOBAL_CHANNELS=19;
constexpr size_t SPATIAL_VALUES=22*19*19, GLOBAL_VALUES=19;
template <typename F> F symbol(void* lib,const char* name) {
    void* address=dlsym(lib,name);
    if(!address)throw std::runtime_error(std::string("Missing Neuron API: ")+name);
    return reinterpret_cast<F>(address);
}
void verify(int rc,const char* description) {
    if(rc)throw std::runtime_error(std::string(description)+" rc="+std::to_string(rc));
}
void raise(JNIEnv* env,const char* cls,const std::string& message) {
    jclass type=env->FindClass(cls);
    if(type)env->ThrowNew(type,message.c_str());
}
void load(std::ifstream& in,void* ptr,size_t length) {
    if(length==0)return;
    in.read(static_cast<char*>(ptr),length);
    if(!in)throw std::runtime_error("Truncated KataGo Neuron packet");
}
uint32_t getU32(std::ifstream& f) {
    uint32_t n=0;load(f,&n,4);return n;
}
struct Operand {
    uint32_t type=0,flags=0;
    std::vector<uint32_t> dimensions;
    std::vector<char> constantData;
};
struct Operation {
    uint32_t opcode;
    std::vector<uint32_t> inputs,outputs;
};
struct Packet {
    std::vector<Operand> operands;
    std::vector<Operation> operations;
    std::vector<uint32_t> inputs,outputs;
};
size_t elements(const Operand& value) {
    size_t count=1;
    for(uint32_t d:value.dimensions) {
        if(!d || count>10000000/d)throw std::runtime_error("Invalid Neuron tensor size");
        count*=d;
    }
    return count;
}
Packet parse(const std::string& filename) {
    std::ifstream file(filename,std::ios::binary);
    if(!file)throw std::runtime_error("KataGo model packet not found: "+filename);
    char header[8]={};
    load(file,header,8);
    if(std::memcmp(header,"K10NW001",8))throw std::runtime_error("Invalid KataGo Neuron packet signature");
    uint32_t operands=getU32(file), operations=getU32(file), inputs=getU32(file), outputs=getU32(file);
    if(operands<100||operands>2000||operations<100||operations>1000||inputs!=2||outputs!=5)
        throw std::runtime_error("Unexpected KataGo 10b graph structure");
    Packet packet;
    packet.operands.reserve(operands);
    for(uint32_t i=0;i<operands;i++) {
        Operand op;
        uint32_t rank=0,bytes=0;
        op.type=getU32(file);rank=getU32(file);op.flags=getU32(file);bytes=getU32(file);
        uint32_t four[4]={};load(file,four,16);
        if(rank>4||bytes>32*1024*1024)throw std::runtime_error("Invalid operand header");
        op.dimensions.assign(four,four+rank);
        op.constantData.resize(bytes);
        load(file,op.constantData.data(),bytes);
        if((op.flags&(CONST_FLAG|INPUT_FLAG))&&
           bytes!=elements(op)*(op.type==8?2:(op.type==6?1:4)))
            throw std::runtime_error("Incorrect serialized constant length at operand "+std::to_string(i));
        packet.operands.push_back(std::move(op));
    }
    packet.operations.reserve(operations);
    for(uint32_t i=0;i<operations;i++) {
        Operation op{};
        op.opcode=getU32(file);
        uint32_t nin=getU32(file),nout=getU32(file);
        if(nin<1||nin>32||nout!=1)throw std::runtime_error("Invalid operation arity");
        op.inputs.resize(nin);op.outputs.resize(nout);
        load(file,op.inputs.data(),nin*4);load(file,op.outputs.data(),nout*4);
        for(uint32_t id:op.inputs)if(id>=operands)throw std::runtime_error("Invalid operation input index");
        for(uint32_t id:op.outputs)if(id>=operands)throw std::runtime_error("Invalid operation output index");
        packet.operations.push_back(std::move(op));
    }
    packet.inputs.resize(inputs);packet.outputs.resize(outputs);
    load(file,packet.inputs.data(),inputs*4);load(file,packet.outputs.data(),outputs*4);
    for(uint32_t id:packet.inputs)if(id>=operands)throw std::runtime_error("Invalid KataGo input index");
    for(uint32_t id:packet.outputs)if(id>=operands)throw std::runtime_error("Invalid KataGo output index");
    for(uint32_t i=0;i<outputs;i++) {
        uint32_t nameSize=getU32(file);
        if(nameSize>256)throw std::runtime_error("Output name too long");
        std::string name(nameSize,'\0');
        if(nameSize)load(file,&name[0],nameSize);
        uint32_t floatBytes=getU32(file);
        if(floatBytes!=elements(packet.operands[packet.outputs[i]])*4)
            throw std::runtime_error("Invalid reference output "+name);
        file.seekg(floatBytes,std::ios::cur); // Benchmark CPU reference, not used for real-game execution
        if(!file)throw std::runtime_error("Truncated KataGo output reference");
    }
    const std::vector<uint32_t> expectedSpatial={1,19,19,22},expectedGlobal={1,1,1,19};
    if(packet.operands[packet.inputs[0]].dimensions!=expectedSpatial||
       packet.operands[packet.inputs[1]].dimensions!=expectedGlobal)
        throw std::runtime_error("This MDLA backend requires 19x19, spatial 22ch and global 19ch");
    static const size_t expectedOutputs[]={1,361,3,4,361};
    for(size_t i=0;i<packet.outputs.size();i++) {
        if(elements(packet.operands[packet.outputs[i]])!=expectedOutputs[i])
            throw std::runtime_error("Unexpected KataGo policy/value/ownership output dimension");
    }
    return packet;
}

class Session {
public:
    explicit Session(const std::string& filename):packet(parse(filename)) {
        try {
            lib=dlopen("libneuronusdk_adapter.9.mtk.so",RTLD_NOW|RTLD_LOCAL);
            if(!lib)lib=dlopen("libneuronusdk_adapter.mtk.so",RTLD_NOW|RTLD_LOCAL);
            if(!lib)throw std::runtime_error("MediaTek Neuron Adapter 9 not available on this Android device");
            getCount=symbol<int (*)(uint32_t*)>(lib,"Neuron_getDeviceCount");
            getDevice=symbol<int (*)(uint32_t,NeuronDevice**)>(lib,"Neuron_getDevice");
            getName=symbol<int (*)(const NeuronDevice*,const char**)>(lib,"NeuronDevice_getName");
            createModel=symbol<int (*)(NeuronModel**)>(lib,"NeuronModel_create");
            freeModel=symbol<void (*)(NeuronModel*)>(lib,"NeuronModel_free");
            addOperand=symbol<int (*)(NeuronModel*,const NeuronOperandType*)>(lib,"NeuronModel_addOperand");
            setOperand=symbol<int (*)(NeuronModel*,int32_t,const void*,size_t)>(lib,"NeuronModel_setOperandValue");
            addOperation=symbol<int (*)(NeuronModel*,int32_t,uint32_t,const uint32_t*,uint32_t,const uint32_t*)>(lib,"NeuronModel_addOperation");
            setIO=symbol<int (*)(NeuronModel*,uint32_t,const uint32_t*,uint32_t,const uint32_t*)>(lib,"NeuronModel_identifyInputsAndOutputs");
            finishModel=symbol<int (*)(NeuronModel*)>(lib,"NeuronModel_finish");
            isSupported=symbol<int (*)(const NeuronModel*,const NeuronDevice* const*,uint32_t,bool*)>(lib,"NeuronModel_getSupportedOperationsForDevices");
            createCompilation=symbol<int (*)(NeuronModel*,const NeuronDevice* const*,uint32_t,NeuronCompilation**)>(lib,"NeuronCompilation_createForDevices");
            finishCompilation=symbol<int (*)(NeuronCompilation*)>(lib,"NeuronCompilation_finish");
            freeCompilation=symbol<void (*)(NeuronCompilation*)>(lib,"NeuronCompilation_free");
            createExecution=symbol<int (*)(NeuronCompilation*,NeuronExecution**)>(lib,"NeuronExecution_create");
            freeExecution=symbol<void (*)(NeuronExecution*)>(lib,"NeuronExecution_free");
            setInput=symbol<int (*)(NeuronExecution*,int32_t,const NeuronOperandType*,const void*,size_t)>(lib,"NeuronExecution_setInput");
            setOutput=symbol<int (*)(NeuronExecution*,int32_t,const NeuronOperandType*,void*,size_t)>(lib,"NeuronExecution_setOutput");
            compute=symbol<int (*)(NeuronExecution*)>(lib,"NeuronExecution_compute");

            uint32_t count=0;verify(getCount(&count),"Neuron_getDeviceCount");
            if(count>64)throw std::runtime_error("Unreasonable Neuron device count");
            NeuronDevice* mdla=nullptr;
            for(uint32_t i=0;i<count;i++) {
                NeuronDevice* dev=nullptr;const char* name=nullptr;
                verify(getDevice(i,&dev),"Neuron_getDevice");
                verify(getName(dev,&name),"NeuronDevice_getName");
                if(name && std::strcmp(name,"mtk-mdla")==0)mdla=dev;
            }
            if(!mdla)throw std::runtime_error("mtk-mdla unavailable (no silent CPU/DSP fallback)");
            const NeuronDevice* devices[]={mdla};
            verify(createModel(&model),"NeuronModel_create");
            for(size_t i=0;i<packet.operands.size();i++) {
                const Operand& item=packet.operands[i];
                NeuronOperandType spec={int32_t(item.type),uint32_t(item.dimensions.size()),
                                       item.dimensions.empty()?nullptr:item.dimensions.data(),0,0};
                verify(addOperand(model,&spec),"NeuronModel_addOperand");
                if(item.flags&CONST_FLAG)
                    verify(setOperand(model,int32_t(i),item.constantData.data(),item.constantData.size()),
                           "NeuronModel_setOperandValue");
            }
            for(size_t i=0;i<packet.operations.size();i++) {
                const Operation& op=packet.operations[i];
                int rc=addOperation(model,int32_t(op.opcode),op.inputs.size(),op.inputs.data(),
                                    op.outputs.size(),op.outputs.data());
                if(rc)throw std::runtime_error("NeuronModel_addOperation index="+std::to_string(i)+
                                                " type="+std::to_string(op.opcode)+" rc="+std::to_string(rc));
            }
            verify(setIO(model,packet.inputs.size(),packet.inputs.data(),packet.outputs.size(),packet.outputs.data()),
                   "NeuronModel_identifyInputsAndOutputs");
            verify(finishModel(model),"NeuronModel_finish");
            std::unique_ptr<bool[]> supports(new bool[packet.operations.size()]{});
            verify(isSupported(model,devices,1,supports.get()),"NeuronModel_getSupportedOperationsForDevices");
            for(size_t i=0;i<packet.operations.size();i++)
                if(!supports[i])throw std::runtime_error("MDLA unsupported KataGo operator "+std::to_string(i));
            verify(createCompilation(model,devices,1,&compilation),"NeuronCompilation_createForDevices");
            verify(finishCompilation(compilation),"NeuronCompilation_finish");
            verify(createExecution(compilation,&execution),"NeuronExecution_create");
            inputSpatial.resize(SPATIAL_VALUES);
            inputGlobal.resize(GLOBAL_VALUES);
            outputBuffers.resize(packet.outputs.size());
            for(size_t i=0;i<packet.outputs.size();i++) {
                outputBuffers[i].resize(elements(packet.operands[packet.outputs[i]]));
                verify(setOutput(execution,int32_t(i),nullptr,outputBuffers[i].data(),
                                 outputBuffers[i].size()*sizeof(uint16_t)),"NeuronExecution_setOutput");
            }
        } catch(...) {
            release();
            throw;
        }
    }
    ~Session() { release(); }
    Session(const Session&)=delete;
    Session& operator=(const Session&)=delete;

    void evaluate(const std::vector<float>& spatial,const std::vector<float>& global,
                  std::vector<std::vector<float>>& outputs) {
        std::lock_guard<std::mutex> guard(mutex);
        if(spatial.size()!=SPATIAL_VALUES||global.size()!=GLOBAL_VALUES)
            throw std::invalid_argument("Expected NCHW [1,22,19,19] and global [1,19,1,1] FP32 features");
        for(size_t i=0;i<SPATIAL_VALUES;i++) {
            size_t channel=i/(BOARD_SIZE*BOARD_SIZE),pixel=i%(BOARD_SIZE*BOARD_SIZE);
            putHalf(inputSpatial[pixel*SPATIAL_CHANNELS+channel],spatial[i]);
        }
        for(size_t i=0;i<GLOBAL_VALUES;i++)putHalf(inputGlobal[i],global[i]);
        verify(setInput(execution,0,nullptr,inputSpatial.data(),inputSpatial.size()*2),"NeuronExecution_setInput(spatial)");
        verify(setInput(execution,1,nullptr,inputGlobal.data(),inputGlobal.size()*2),"NeuronExecution_setInput(global)");
        verify(compute(execution),"NeuronExecution_compute");
        outputs.clear();
        for(size_t index=0;index<packet.outputs.size();index++) {
            const Operand& operand=packet.operands[packet.outputs[index]];
            const auto& half=outputBuffers[index];
            std::vector<float> result(half.size());
            // Convert NHWC outputs back to the exact original KataGo NCHW ordering.
            if(operand.dimensions.size()==4) {
                size_t H=operand.dimensions[1],W=operand.dimensions[2],C=operand.dimensions[3];
                for(size_t y=0;y<H;y++)for(size_t x=0;x<W;x++)for(size_t c=0;c<C;c++)
                    result[(c*H+y)*W+x]=toFloat(half[(y*W+x)*C+c]);
            } else {
                for(size_t i=0;i<half.size();i++)result[i]=toFloat(half[i]);
            }
            outputs.push_back(std::move(result));
        }
    }

private:
    using FGetCount=int (*)(uint32_t*);
    FGetCount getCount=nullptr;
    int (*getDevice)(uint32_t,NeuronDevice**)=nullptr;
    int (*getName)(const NeuronDevice*,const char**)=nullptr;
    int (*createModel)(NeuronModel**)=nullptr;
    void (*freeModel)(NeuronModel*)=nullptr;
    int (*addOperand)(NeuronModel*,const NeuronOperandType*)=nullptr;
    int (*setOperand)(NeuronModel*,int32_t,const void*,size_t)=nullptr;
    int (*addOperation)(NeuronModel*,int32_t,uint32_t,const uint32_t*,uint32_t,const uint32_t*)=nullptr;
    int (*setIO)(NeuronModel*,uint32_t,const uint32_t*,uint32_t,const uint32_t*)=nullptr;
    int (*finishModel)(NeuronModel*)=nullptr;
    int (*isSupported)(const NeuronModel*,const NeuronDevice* const*,uint32_t,bool*)=nullptr;
    int (*createCompilation)(NeuronModel*,const NeuronDevice* const*,uint32_t,NeuronCompilation**)=nullptr;
    int (*finishCompilation)(NeuronCompilation*)=nullptr;
    void (*freeCompilation)(NeuronCompilation*)=nullptr;
    int (*createExecution)(NeuronCompilation*,NeuronExecution**)=nullptr;
    void (*freeExecution)(NeuronExecution*)=nullptr;
    int (*setInput)(NeuronExecution*,int32_t,const NeuronOperandType*,const void*,size_t)=nullptr;
    int (*setOutput)(NeuronExecution*,int32_t,const NeuronOperandType*,void*,size_t)=nullptr;
    int (*compute)(NeuronExecution*)=nullptr;
    void* lib=nullptr;
    NeuronModel* model=nullptr;
    NeuronCompilation* compilation=nullptr;
    NeuronExecution* execution=nullptr;
    Packet packet;
    std::mutex mutex;
    std::vector<uint16_t> inputSpatial,inputGlobal;
    std::vector<std::vector<uint16_t>> outputBuffers;
    static void putHalf(uint16_t& dst,float value) {
        if(!std::isfinite(value))throw std::invalid_argument("Non-finite KataGo feature value");
        _Float16 half=static_cast<_Float16>(value);
        std::memcpy(&dst,&half,sizeof(dst));
    }
    static float toFloat(uint16_t bits) {
        _Float16 half;
        std::memcpy(&half,&bits,sizeof(bits));
        return float(half);
    }
    void release() {
        if(execution && freeExecution)freeExecution(execution);
        if(compilation && freeCompilation)freeCompilation(compilation);
        if(model && freeModel)freeModel(model);
        if(lib)dlclose(lib);
        execution=nullptr;compilation=nullptr;model=nullptr;lib=nullptr;
    }
};
} // namespace

extern "C" JNIEXPORT jlong JNICALL
Java_com_badukai_engine_NeuronKataGoBackend_nativeOpen(JNIEnv* env,jclass,jstring jpath) {
    if(!jpath){raise(env,"java/lang/IllegalArgumentException","modelPath is null");return 0;}
    const char* path=env->GetStringUTFChars(jpath,nullptr);
    if(!path)return 0;
    const std::string filename(path);
    env->ReleaseStringUTFChars(jpath,path);
    try {
        return reinterpret_cast<jlong>(new Session(filename));
    } catch(const std::exception& e) {
        raise(env,"java/lang/IllegalStateException",e.what());
        return 0;
    }
}
extern "C" JNIEXPORT jobjectArray JNICALL
Java_com_badukai_engine_NeuronKataGoBackend_nativeEvaluate(
        JNIEnv* env,jclass,jlong nativeHandle,jfloatArray spatial,jfloatArray global) {
    if(!nativeHandle||!spatial||!global){
        raise(env,"java/lang/IllegalArgumentException","Session and both features are required");
        return nullptr;
    }
    if(env->GetArrayLength(spatial)!=SPATIAL_VALUES||env->GetArrayLength(global)!=GLOBAL_VALUES) {
        raise(env,"java/lang/IllegalArgumentException","Expected spatial[7942] and global[19] NCHW features");
        return nullptr;
    }
    try {
        std::vector<float> source(SPATIAL_VALUES),extra(GLOBAL_VALUES);
        env->GetFloatArrayRegion(spatial,0,source.size(),source.data());
        if(env->ExceptionCheck())return nullptr;
        env->GetFloatArrayRegion(global,0,extra.size(),extra.data());
        if(env->ExceptionCheck())return nullptr;
        auto* session=reinterpret_cast<Session*>(nativeHandle);
        std::vector<std::vector<float>> results;
        session->evaluate(source,extra,results);
        jclass floatArrayClass=env->FindClass("[F");
        if(!floatArrayClass)return nullptr;
        jobjectArray arr=env->NewObjectArray(results.size(),floatArrayClass,nullptr);
        if(!arr)return nullptr;
        for(size_t i=0;i<results.size();i++) {
            jfloatArray row=env->NewFloatArray(results[i].size());
            if(!row)return nullptr;
            env->SetFloatArrayRegion(row,0,results[i].size(),results[i].data());
            if(env->ExceptionCheck()){env->DeleteLocalRef(row);return nullptr;}
            env->SetObjectArrayElement(arr,i,row);
            env->DeleteLocalRef(row);
            if(env->ExceptionCheck())return nullptr;
        }
        return arr;
    } catch(const std::invalid_argument& e) {
        raise(env,"java/lang/IllegalArgumentException",e.what());
    } catch(const std::exception& e) {
        raise(env,"java/lang/IllegalStateException",e.what());
    }
    return nullptr;
}
extern "C" JNIEXPORT void JNICALL
Java_com_badukai_engine_NeuronKataGoBackend_nativeClose(JNIEnv*,jclass,jlong nativeHandle) {
    delete reinterpret_cast<Session*>(nativeHandle);
}
